package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.pasienview;
import view.dokterview;
import view.poliview;
import view.rekamedikview;

/**
 *
 * @author HP
 */
public class awal extends javax.swing.JFrame {
    
    public awal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPasien = new javax.swing.JButton();
        ButtonDokter = new javax.swing.JButton();
        ButtonPoli = new javax.swing.JButton();
        ButtonRekamedik = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPasien.setText("PASIEN");
        ButtonPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPasienActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, 80));

        ButtonDokter.setText("DOKTER");
        ButtonDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDokterActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 200, 80));

        ButtonPoli.setText("POLI");
        ButtonPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPoliActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, 80));

        ButtonRekamedik.setText("REKAMEDIK");
        ButtonRekamedik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRekamedikActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRekamedik, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 200, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("SELAMAT DATANG DI SISTEM INFORMASI PUSKESMAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 484, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\Saved Pictures\\images (1).jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPasienActionPerformed
       try {
            pasienview PS = new pasienview();
            PS.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(awal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonPasienActionPerformed

    private void ButtonDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDokterActionPerformed
        try {
            dokterview DKW = new dokterview();
            DKW.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(awal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonDokterActionPerformed

    private void ButtonPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPoliActionPerformed
        try {
            poliview PL = new poliview();
            PL.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(awal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonPoliActionPerformed

    private void ButtonRekamedikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRekamedikActionPerformed
       try {
            rekamedikview RKM = new rekamedikview();
            RKM.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(awal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonRekamedikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDokter;
    private javax.swing.JButton ButtonPasien;
    private javax.swing.JButton ButtonPoli;
    private javax.swing.JButton ButtonRekamedik;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
